---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pii-collector
spec:
  params:
    - name: ids-token
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  workspaces:
    - name: workspace
      description: A workspace where the app is to be expected
      mountPath: /artifacts
  steps:
    - name: pii-collector
      image: alpine/git
      workingDir: /artifacts
      env:
        - name: HOME
          value: "/root"
        - name: TOKENIDS
          value: $(params.ids-token)
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      script: |
        #!/bin/sh
        
        ls
        echo "***************"
        pwd
        cd /artifacts
        pwd
        git clone --depth 1 "https://$TOKENIDS@github.ibm.com/org-ids/pii"
        chmod -R 777 pii/run
        #./pii/run
        REPO_URL=$(git config --get remote.origin.url | sed -E "s/^.*(@|\/\/)([^:\/]+)(\/|:)(.+)$/https:\/\/\2\/\4/" | sed -E "s/^(.*)\.git$/\1/")
        REPO_NAME=${REPO_URL##*/}
        echo "REPO_URL $REPO_URL"
        echo "REPO_NAME $REPO_NAME"
        ls pii