---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pii-collector
spec:
  params:
    - name: ids-token
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  workspaces:
    - name: workspace
      description: A workspace where the Dockerfile is expected to be
      mountPath: /artifacts
  steps:
    - name: check-dockerfile
      image: alpine/git
      workingDir: /artifacts
      env:
        - name: IDS_TOKEN
          value: $(params.ids-token)
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      script: |
        #!/bin/sh
        if [ $PIPELINE_DEBUG == 1 ]; then
          pwd
          env
          hadolint --version
          trap env EXIT
          set -x
        fi
        ls
        echo "***************"
        git clone --depth 1 "https://$TOKENIDS@github.ibm.com/org-ids/pii"
        #pii/run
        ls