apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pii-task
spec:
  params:
    - name: token-ids
      description: token id
  steps:
    - name: update-pii-repo
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: TOKENIDS
          value: $(params.token-ids)
      script: |
          #!/bin/bash
          echo "RUNNING"
          echo "$TOKENIDS"
          ls
          ls /artifacts
  workspaces:
  - name: artifacts
    description: A workspace backing by a volume
    mountPath: /artifacts
      
