---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: linter-docker-lint
spec:
  params:
    - name: path-to-dockerfile
      default: .
    - name: dockerfile
      description: The name of the Dockerfile
      default: "Dockerfile"
    - name: path-to-hadolint-config
      default: ""
    - name: hadolint-ignored-rules
      default: ""
    - name: trusted-registries
      default: ""
    - name: fail-on-lint-errors
      description: |
        flag (`true` | `false`) to indicate if the task should fail or continue
        if issues are found in the Dockerfile lint
      default: "true"
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  workspaces:
    - name: workspace
      description: A workspace where the Dockerfile is expected to be
      mountPath: /artifacts
  steps:
    - name: check-dockerfile
      image: hadolint/hadolint:v1.18.0-alpine
      workingDir: /artifacts
      env:
        - name: DOCKER_FILE
          value: $(params.dockerfile)
        - name: DOCKER_FILE_PATH
          value: $(params.path-to-dockerfile)
        - name: HADOLINT_CONFIG
          value: $(params.path-to-hadolint-config)
        - name: HADOLINT_IGNORED_RULES
          value: $(params.hadolint-ignored-rules)
        - name: TRUSTED_REGISTRIES
          value: $(params.trusted-registries)
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      script: |
        #!/bin/sh
        if [ $PIPELINE_DEBUG == 1 ]; then
          pwd
          env
          hadolint --version
          trap env EXIT
          set -x
        fi
        ls
        echo "path : $DOCKER_FILE_PATH"