---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pii-collector
spec:
  params:
    - name: ids-token
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  workspaces:
    - name: workspace
      description: A workspace where the app is to be expected
      mountPath: /artifacts
  steps:
    - name: pii-collector
      image: alpine/git
      workingDir: /artifacts
      env:
        - name: TOKENIDS
          value: $(params.ids-token)
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      script: |
        #!/bin/sh
        
        ls
        echo "***************"
        #cd /artifacts
        git clone --depth 1 "https://$TOKENIDS@github.ibm.com/org-ids/pii"
        chmod -R 777 pii/run
        #pii/run
        ls